export const SPECIALTIES = {
    foodAndDrinks: 'Alimentos y bebidas',
    accounting: 'Aplicación de Normas y Procedimientos Contables y Fiscales',
    administration: 'Administración',
    educationalAssistence: 'Asistencia Educativa Inicial y Preescolar',
    executiveAssistence: 'Asistencia Ejecutiva',
    cosmetology: 'Cuidados Cosmetológicos Faciales y Corporales',
    styling: 'Estilismo y Diseño de Imagen',
    digitalGraphic: 'Expresión Gráfica Digital',
    computing: 'Informática',
    technicalSupport: 'Soporte Técnico a Equipos y Sistemas Computacionales',
    english: 'Uso de la Lengua Inglesa en Diversos Contextos ',
    bodyWork: 'Diseño e Imagen de la Carrocería',
    tourist: 'Gestión y Venta de Servicios Turísticos',
    hospitality: 'Hotelería',
    electronicSystem: 'Mantenimiento a Equipos y Sistemas Electrónicos',
    autoElectrical: 'Mantenimiento al Sistema Eléctrico Automotriz',
    autoElectronic: 'Mantenimiento al Sistema Electrónico Automotriz',
    autoElectromechanical: 'Mantenimiento Electromecánico del Automóvil',
    dieselMechanics: 'Mecánica Diesel',
}